version: '3'

services:
    dev:
        build: .
        environment:
            - DISPLAY
        hostname: pkos_dev
        volumes:
            - .:/pkos
        network_mode: 'host'
        entrypoint: ["make", "clean", "run"]


