version: '3'

services:
    dev:
        build: .
        environment:
            - DISPLAY
        hostname: pkos_dev
        volumes:
            - .:/pkos
            - /tmp:/tmp
        network_mode: 'host'
        entrypoint: tail -f /dev/null

