version: '3'

services:
    dev:
        build: .
        environment:
            - DISPLAY
        hostname: pkos_dev
        volumes:
            - .:/pkos
        network_mode: 'host' # makes x11 windows work for `make run`
        entrypoint: ['make', 'run']